import type { Metadata } from 'next';
import { Comfortaa, Frank_Ruhl_Libre } from 'next/font/google';

import './globals.css';

const raleway = Comfortaa({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-raleway',
});

const frank = Frank_Ruhl_Libre({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-frank',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${raleway.variable} ${frank.variable}`}
    >
      <body className='font-raleway'>{children}</body>
    </html>
  );
}
